pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/-la-checklist-ultime-pour-rend.mp4 --props='{"title":"📝 ✅ La checklist ultime pour rendre vos applications cloud native !","speakers":[{"name":"Katia HIMEUR","picture":"https://avatars.githubusercontent.com/u/40885659?v=4"}],"date":"20 Octobre","time":"14h00","location":"Belem"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/30-index-sur-une-table-pg-de-6.mp4 --props='{"title":"30 index sur une table PG de 6To : défis et solutions","speakers":[{"name":"Flora Briand","picture":"https://lh3.googleusercontent.com/a/AGNmyxbfVdDsKpiI5nsCGBo9CAaVkbWuYev0EsmvNxgy6A=s96-c"}],"date":"20 Octobre","time":"11h20","location":"Belem"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/5M0ZZ0DwzKzP4tXhQygR.mp4 --props='{"title":"Apache Kafka & Apache Flink - Better Together","speakers":[{"name":"Konstantin Knauf","picture":"https://i.ibb.co/sP5RJn6/Konstantin-Knauf.jpg"}],"date":"20 Octobre","time":"10h10","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/MU9g0zWv1eBXiS1dRAHK.mp4 --props='{"title":"Le micropython serpent peu connu dans la jungle IOT","speakers":[{"name":"Guillaume Hourdier","picture":"https://github.com/GDG-Nantes/Devfest2023/assets/525974/998c9eb4-4e39-49e8-b980-36a20ad3982e"},{"name":"Baptiste Candalh","picture":"https://github.com/GDG-Nantes/Devfest2023/assets/525974/24c7635b-8190-48cb-89ed-15701fda6bf5"}],"date":"20 Octobre","time":"16h50","location":"Tour Bretagne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/WkhPA3bKzt3aKySVJzJj.mp4 --props='{"title":"Keynote Ouverture","speakers":[{"name":"Speaker Keynote Ouverture","picture":"TODO"}],"date":"19 Octobre","time":"9h00","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/XKzOPv0xT4NwgMQIrPoj.mp4 --props='{"title":"Keynote Fermeture","speakers":[{"name":"Speaker Keynote Fermeture","picture":"TODO"}],"date":"20 Octobre","time":"17h20","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/a-small-leak-can-sink-a-great-.mp4 --props='{"title":"A small leak can sink a great ship","speakers":[{"name":"Ayushi Gupta","picture":"https://lh3.googleusercontent.com/a/AGNmyxY_6f9aFIJwv9xZzYibDu2pjPPAVgTFPfY_gXPXpdM=s96-c"}],"date":"19 Octobre","time":"15h10","location":"Belem"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/alfredo-linguini-et-les-modele.mp4 --props='{"title":"Alfredo Linguini et les Modèles Génératifs : Qui Fait Vraiment la Cuisine ?","speakers":[{"name":"Yann Carbonne","picture":"https://lh3.googleusercontent.com/a/AAcHTtcUisccrnngpC_MRToEgnWJSI464jy19j-njJm5=s96-c"}],"date":"20 Octobre","time":"15h10","location":"Tour Bretagne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/angular-signals-how-do-they-wo.mp4 --props='{"title":"Angular Signals : how do they work ?","speakers":[{"name":"Benjamin Legrand","picture":"https://avatars.githubusercontent.com/u/32519406?v=4"}],"date":"20 Octobre","time":"16h20","location":"Titan"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/apprenons-ensemble-grace-aux-b.mp4 --props='{"title":"Apprenons ensemble grâce aux bookclubs","speakers":[{"name":"Marion Valentin","picture":"https://lh3.googleusercontent.com/a-/AOh14Gjo3eiLyQDK6oAv9VdYz0cm6wlg_ZJ1jxhho5Fn=s96-c"},{"name":"Yvonnick FRIN","picture":"https://lh5.googleusercontent.com/-tmj1tGCN_u4/AAAAAAAAAAI/AAAAAAAABO0/oVqsblFTX8k/photo.jpg"}],"date":"20 Octobre","time":"16h20","location":"Belem"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/apres-lordi-8-bit-voici-la-car.mp4 --props='{"title":"Après l'\''ordi 8 bit voici la carte VGA sur breadboard","speakers":[{"name":"Olivier HUBER","picture":"https://avatars0.githubusercontent.com/u/650681?v=4"}],"date":"19 Octobre","time":"11h10","location":"Titan"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/asdf-un-outil-pour-toutes-vos-.mp4 --props='{"title":"asdf, un outil pour toutes vos versions","speakers":[{"name":"Sylvain METAYER","picture":"https://avatars.githubusercontent.com/u/8873695?v=4"}],"date":"19 Octobre","time":"17h50","location":"Tour Bretagne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/au-secours-jai-une-personne-ha.mp4 --props='{"title":"Au secours, j'\''ai une personne handicapée dans mon équipe !","speakers":[{"name":"Emmanuelle ABOAF","picture":"https://lh3.googleusercontent.com/a-/AOh14GgwiE4A4acIJAZk6f-90gF6CawNDjo6arOeTZr2zQ=s96-c"}],"date":"20 Octobre","time":"11h20","location":"Titan"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/breaking-up-long-tasks.mp4 --props='{"title":"🇺🇸Breaking up long tasks","speakers":[{"name":"Nishu Goel","picture":"https://avatars.githubusercontent.com/u/26349046?v=4"}],"date":"19 Octobre","time":"11h10","location":"Belem"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/bullet-train-code-le-jeu-inspi.mp4 --props='{"title":"Bullet train: code le jeu inspiré du film avec Flutter et Flame","speakers":[{"name":"Jocelyn Griselle","picture":"https://i.ibb.co/MD8cmvC/jocelyn.jpg"},{"name":"Emmanuel LEFEBVRE DIBON","picture":"https://github.com/GDG-Nantes/Devfest2023/assets/525974/cdc0ac09-e4c8-4324-9c34-5841bb0a93fd"},{"name":"Adrien Body","picture":"https://cache.sessionize.com/image/4e2b-200o200o2-PoDWkJtRXHSr6yhs1VybE2.jpeg"}],"date":"20 Octobre","time":"14h00","location":"Hangar"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/changer-son-environnement-full.mp4 --props='{"title":"Changer son environnement fullstack en un clin d'\''oeil avec devenv","speakers":[{"name":"Julien Tanguy","picture":"https://www.gravatar.com/avatar/f0e2508a08ad22fb0cc5baab1dec2832"},{"name":"Anthony Pena","picture":"https://avatars.githubusercontent.com/u/2668904?v=4"}],"date":"19 Octobre","time":"14h00","location":"Hangar"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/cloudbusters-a-la-chasse-des-c.mp4 --props='{"title":"Cloudbusters : À la Chasse des Coûts Fantômes","speakers":[{"name":"Omar KAMMOUN","picture":"https://lh3.googleusercontent.com/a/AAcHTtfpW3FWr2zEq-NsR82Ao8LDyPTVzdR4NZBC_ZnqnA=s96-c"}],"date":"19 Octobre","time":"10h00","location":"Titan"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/comment-hacker-vos-application.mp4 --props='{"title":"Comment hacker vos applications mobiles ?","speakers":[{"name":"Amélie Avignon","picture":"https://github.com/GDG-Nantes/Devfest2023/assets/525974/b1bc8d41-63a7-4384-89b7-3a65dcec37d0"},{"name":"Julien Jimenez","picture":"https://github.com/GDG-Nantes/Devfest2023/assets/525974/06370b2e-e04b-4a39-892d-30e9110260ea"}],"date":"19 Octobre","time":"14h00","location":"Belem"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/comment-les-interfaces-nous-ma.mp4 --props='{"title":"Comment les interfaces nous manipulent !","speakers":[{"name":"Flora Brochier","picture":"https://lh3.googleusercontent.com/a/AAcHTtdCKtNOBrUW9rbIrtgNb32Tk_3QL2gSKcWASp7X=s96-c"}],"date":"20 Octobre","time":"16h20","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/construisez-une-data-platform-.mp4 --props='{"title":"Construisez une Data Platform Cloud Native sur Google Cloud","speakers":[{"name":"Fabien Portes","picture":"https://lh3.googleusercontent.com/a/AGNmyxYaa93xNOe5yhrpgkQN-oW1IQuZCj-fe4s_beM3Lj4=s96-c"},{"name":"Matthieu Grandrie","picture":"https://lh3.googleusercontent.com/a-/AOh14Gh5AAWnLTOUCAZuunFSdaG6N41t2S_AJS_5vdgYZKYcL_cmPRmNGGJ5aYtYXSY0AyBm9nsg4fHj5vxh58tVOKO537NnHJhTZ0UQo2MBx-HTVUduz97Y788f6UcQw7xPPmEhVvs61X2xKHAa-FAqX5VmWEBg_SCodJuAAqXZnZP6GjdtSfYc3uL35rSkiSJQiFaxhrT8Ib2HNNNdJgMt8JDsrdZNLEpf3U5Rp1lRm73T5B3jUmf_8bmCPhzn_Rx6ZTHdN5dpWeFoVlm_-lDpjz-7uS-q83p2p_m7yQnwaHsC0k2E_Qjf7Z9Hh9zHN9CeyBX81NbBATXhVZHymzf-Hpf7Y5kNK3nuJmU97h6_Fz8C6Jrg73AAIdvghH882z1G55W8_aRyB1VF74SKULIzj5XG4qfuZhjJpcz86JkLHu_2t8pXcJHeLrnsivFs61WS4TDG5ujEbjh-kYqgBuTgvm26z2Rww2WtIsxBkVrEFCQdtX66469FgyBsT_03JApd8C4DbzTGRDjxIWugObrpFodqKVbFnn1w3B3mH8-NCdfyZ4aCZko375D090V4nGgPuPUUrr3k7lD8OJpqVOR7IYRUoq1QpUBNKa3wRf68NuWJKsQbxYzsKrwKOG38c7MKrBekPxRoAxp1bGPR524jpDeKysIswZWax3OJTmZgTB_GHq4fEXLOZq8cdvlfMs4YXaCAR1n01rv3cmGFXe7-cQcKV0wtYvbHS0oheiadJQccLD5SBF3wrd3gr2teNRQnxZk0Fw=s96-c"},{"name":"Clément Bosc","picture":"https://lh3.googleusercontent.com/a-/AOh14Gh8JUVcMJ1VzwLiDM5oqtY7H3NmhL-yYwDRiGFE7Q4=s96-c"}],"date":"19 Octobre","time":"14h00","location":"L'\''Atelier"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/core-web-vitals-mettez-votre-a.mp4 --props='{"title":"Core Web Vitals: Mettez votre application sur orbite avec les meilleurs pratiques","speakers":[{"name":"Nicolas FRIZZARIN","picture":"https://lh4.googleusercontent.com/-QZhPN3UNDBA/AAAAAAAAAAI/AAAAAAAAAEs/Ki7Avw5jkKg/photo.jpg"}],"date":"20 Octobre","time":"10h10","location":"Titan"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/css-renait-de-ses-cendres-rede.mp4 --props='{"title":"CSS renaît de ses cendres: (re)devenez copains avec votre feuille de style","speakers":[{"name":"Olivier Leplus","picture":"https://raw.githubusercontent.com/tagazok/tagazok.github.io/master/assets/images/avatar%20olivier.png"},{"name":"Yohan Lasorsa","picture":"https://avatars0.githubusercontent.com/u/593151?v=4"}],"date":"20 Octobre","time":"9h00","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/de-startup-a-entreprise-rentab.mp4 --props='{"title":"De startup à entreprise rentable : quel chemin pour la tech ?","speakers":[{"name":"Ludovic Borie","picture":"https://avatars1.githubusercontent.com/u/1374221?v=4"}],"date":"19 Octobre","time":"14h00","location":"Titan"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/des-secrets-dans-les-pixels-a-.mp4 --props='{"title":"Des secrets dans les pixels ! À la découverte de la stéganographie","speakers":[{"name":"Sonia Seddiki","picture":"https://lh3.googleusercontent.com/a-/AOh14GgSLiScwN2Sftnyc6lF_J9nUPQqlswAA8eyi0IZnA=s96-c"}],"date":"19 Octobre","time":"17h50","location":"Belem"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/design-system-en-pilote-automa.mp4 --props='{"title":"Design System en pilote automatique : du design à la production","speakers":[{"name":"Lauriane Anthony","picture":"https://i.ibb.co/vXyX0XR/2018-07-19-Copie.jpg"}],"date":"19 Octobre","time":"17h50","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/dessine-moi-un-graphique-en-cs.mp4 --props='{"title":"Dessine moi un graphique (en CSS)","speakers":[{"name":"Gaël Poupard","picture":"https://avatars.githubusercontent.com/u/2890570?v=4"}],"date":"19 Octobre","time":"10h00","location":"Belem"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/du-css-aux-shaders-webgl-panor.mp4 --props='{"title":"Du CSS aux shaders WebGL : panorama des techniques d'\''animation en 2023","speakers":[{"name":"Julien Sulpis","picture":"https://avatars2.githubusercontent.com/u/22420399?v=4"}],"date":"20 Octobre","time":"15h10","location":"Belem"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/escape-camp-le-making-of-.mp4 --props='{"title":"Escape Camp 🏃🏕️, Le making of 🎬","speakers":[{"name":"William Bartlett","picture":"https://i.ibb.co/wrFNxYT/Photo-2023-square.jpg"},{"name":"Grégory Bévan","picture":"https://lh6.googleusercontent.com/-rQbmsaYUNxY/AAAAAAAAAAI/AAAAAAAAAAs/XyvhmkEclqs/photo.jpg"},{"name":"Jérémy Lejeune","picture":"https://github.com/GDG-Nantes/Devfest2023/assets/525974/ccf439ff-94f2-4743-876d-c188a6b37147"}],"date":"19 Octobre","time":"16h20","location":"Les Machines"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/et-si-lia-etait-la-solution-po.mp4 --props='{"title":"Et si l'\''IA était la solution pour comprendre la langue des signes ?","speakers":[{"name":"Eléa Petton","picture":"https://avatars.githubusercontent.com/u/78957502?v=4"}],"date":"19 Octobre","time":"15h10","location":"Titan"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/expand-your-view-of-your-appli.mp4 --props='{"title":"Expand your view of your application performance with OpenTelemetry","speakers":[{"name":"Damien Raude-Morvan","picture":"https://pbs.twimg.com/profile_images/467414584169484289/ZhWfTENW_normal.jpeg"}],"date":"19 Octobre","time":"15h10","location":"Tour Bretagne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/exploiting-aws-misconfiguratio.mp4 --props='{"title":"Exploiting AWS Misconfigurations: A Capture the Flag Workshop","speakers":[{"name":"Ben","picture":"https://lh6.googleusercontent.com/1zCaz-rAqhZqJc8eX4sXhVMN5FB7EqUIypKCtl9k52L2pa0dOxzRL2oDcfO4N3QhzM0=w2400"},{"name":"jean verrons","picture":"https://lh4.googleusercontent.com/-cE4tKae2QXfhqbsmD7Qf5mk9pqrbVrgxBeyogM1m21JPbDi0VkMOlCXwCHjKuFqaHI=w2400"}],"date":"19 Octobre","time":"14h00","location":"Les Machines"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/feature-flags-with-openfeature.mp4 --props='{"title":"Feature Flags with OpenFeature: Enabling Faster, More Collaborative Development","speakers":[{"name":"David Hirsch","picture":"https://avatars.githubusercontent.com/u/79513080?v=4"}],"date":"20 Octobre","time":"16h20","location":"Tour Bretagne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/feminisation-de-la-filiere-num.mp4 --props='{"title":"Féminisation de la filière numérique : cassons les codes !","speakers":[{"name":"Stéphanie vachon","picture":"https://lh4.googleusercontent.com/-c7HIKgyk9M0/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckTDyxa2BrNI5au2UmNAj-8pzG02Q/photo.jpg"},{"name":"Mélissa Cottin","picture":"https://www.festival-infolocale.fr/wp-content/uploads/Me%CC%81lissa-Cottin-1024x1024.png"}],"date":"19 Octobre","time":"10h00","location":"L'\''Atelier"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/festival-du-cinema-du-devfest-.mp4 --props='{"title":"Festival du Cinéma du DevFest: Application Web3 avec NFT","speakers":[{"name":"Adrien LASSELLE","picture":"https://lh3.googleusercontent.com/-A7QVhtLGNdI/AAAAAAAAAAI/AAAAAAAABzY/tYaj9OZuIuc/photo.jpg"},{"name":"Vincent Colas","picture":"https://lh3.googleusercontent.com/a/AGNmyxbFlHB9gXxyNtwQaVGx8ACdxuKOTZY_mpcITw_W=s96-c"},{"name":"Bertrand Presles","picture":"https://avatars1.githubusercontent.com/u/220623?v=4"}],"date":"20 Octobre","time":"9h00","location":"L'\''Atelier"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/go-serverless-but-is-it-secure.mp4 --props='{"title":"Go Serverless! But is it secure?","speakers":[{"name":"Natalie Godec","picture":"https://lh3.googleusercontent.com/a-/AOh14Gh5VTtfElfLE0yTSyfCO8a7czDqjrrX8jb4H5Rx=s96-c"}],"date":"20 Octobre","time":"11h20","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/hydration-islands-streaming-re.mp4 --props='{"title":"Hydration, Islands, Streaming, Resumability… Oh My!","speakers":[{"name":"Matheus Albuquerque","picture":"https://i.ibb.co/Db54PQt/matheus.jpg"}],"date":"19 Octobre","time":"16h20","location":"Tour Bretagne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/its-a-testing-trap-common-endt.mp4 --props='{"title":"🇺🇸It'\''s a (testing) trap! - Common end-to-end pitfalls and how to solve them","speakers":[{"name":"Ramona Schwering","picture":"https://lh3.googleusercontent.com/a/AGNmyxZ0qBWdJA7n3gI68UIMzW_a-u0G8uJHwqQUOrZdeA=s96-c"}],"date":"20 Octobre","time":"14h00","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/je-ne-suis-pas-passionnee-et-a.mp4 --props='{"title":"Je ne suis pas passionné(e) et alors ?!","speakers":[{"name":"Helvira Goma","picture":"https://i.ibb.co/Thv7Vkw/UO3hh-XS9-400x400.jpg"}],"date":"20 Octobre","time":"14h00","location":"Tour Bretagne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/jeux-de-donnees-de-mes-environ.mp4 --props='{"title":"Jeux de données de mes environnements hors production : construction ou anonymisation ? ","speakers":[{"name":"Alexis LEGROS","picture":"https://lh3.googleusercontent.com/a/AGNmyxZJWQ8NsqUOb5_YGw7-HGoKby5msW0lVnM2oLy2=s96-c"},{"name":"TJarriault","picture":"https://avatars.githubusercontent.com/u/7701382"}],"date":"19 Octobre","time":"17h20","location":"Tour Bretagne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/la-compression-web-comment-rep.mp4 --props='{"title":"La compression Web : comment (re)prendre le contrôle ?","speakers":[{"name":"Antoine CARON","picture":"https://avatars0.githubusercontent.com/u/6263857?v=4"},{"name":"Hubert SABLONNIERE","picture":"https://lh3.googleusercontent.com/-zULkNj_mgrE/AAAAAAAAAAI/AAAAAAAAmiM/s1x33T4pEBo/photo.jpg"}],"date":"19 Octobre","time":"14h00","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/lagc-retour-sur-lordinateur-qu.mp4 --props='{"title":"L'\''AGC : l'\''ordinateur qui a amené l'\''humanité sur la Lune","speakers":[{"name":"Olivier PONCET","picture":"https://avatars.githubusercontent.com/u/29702924?v=4"},{"name":"Romain BERTHON","picture":"https://avatars2.githubusercontent.com/u/20265323?v=4"}],"date":"20 Octobre","time":"15h10","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/lazy-hydrate-never-hydrate-res.mp4 --props='{"title":"Lazy Hydrate, Never Hydrate, Resumable JS : les astuces des frameworks pour réduire le Total Blocking Time","speakers":[{"name":"Martin Guillier","picture":"https://lh3.googleusercontent.com/a/AAcHTte2jJwmqG5x_MZ7cBOsMDnSRmAdcWM4wQRmjYSe=s96-c"}],"date":"19 Octobre","time":"17h50","location":"Titan"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/le-second-brain-pourquoi-et-co.mp4 --props='{"title":"Le Second Brain,  pourquoi et comment il peut changer votre vie.","speakers":[{"name":"Samuel NAIT","picture":"https://lh3.googleusercontent.com/a/AAcHTtcwyQRXBJmRj0rhO-tYZlzKoWiBOmiOZ26AB3BqbQ=s96-c"}],"date":"19 Octobre","time":"17h20","location":"Titan"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/legoflowgame-le-waterfall-le-s.mp4 --props='{"title":"LegoFlowGame : le Waterfall, le Scrum et le Kanban tu différencieras !","speakers":[{"name":"Fanny Klauk","picture":"https://lh3.googleusercontent.com/a-/AOh14Ghy-jt97zLXbqxsYUcdxvd62hB1katKsxvruKL4"}],"date":"20 Octobre","time":"9h00","location":"Les Machines"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/les-meilleurs-outils-de-dev-so.mp4 --props='{"title":"Les meilleurs outils de dev sont-il dans le Cloud?","speakers":[{"name":"Alexis Moussine-Pouchkine","picture":"https://lh4.googleusercontent.com/-lhM21yfjURo/AAAAAAAAAAI/AAAAAAAAU44/ZvWlMXFvwpc/photo.jpg"}],"date":"19 Octobre","time":"16h20","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/lux-accessible-exploitez-le-po.mp4 --props='{"title":"L'\''UX accessible : Exploitez le potentiel des attributs ARIA","speakers":[{"name":"Gérôme Grignon","picture":"https://pbs.twimg.com/profile_images/1060538989403365376/O8AR92ZR_400x400.jpg"}],"date":"20 Octobre","time":"16h50","location":"Belem"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/mais-au-fait-que-se-passetil-q.mp4 --props='{"title":"Mais au fait, que se passe-t-il quand je mets en ligne une vidéo ?","speakers":[{"name":"Antoine Wacheux","picture":"https://pbs.twimg.com/profile_images/1591071618884931586/HLextC7G_400x400.jpg"}],"date":"19 Octobre","time":"16h20","location":"Belem"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/mission-playwright-the-cypress.mp4 --props='{"title":"Mission: Playwright 🎭, the Cypress killer by Microsoft","speakers":[{"name":"Mathieu Mure","picture":"https://lh3.googleusercontent.com/-zW9q6DSj72k/AAAAAAAAAAI/AAAAAAAAABs/_pqpmU87wFk/photo.jpg"}],"date":"19 Octobre","time":"10h00","location":"Les Machines"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/mlops-une-cicd-pour-des-ia-fia.mp4 --props='{"title":"MLOps : une CI/CD pour des IA fiables","speakers":[{"name":"Ingrid Fiquet","picture":"https://lh3.googleusercontent.com/a/AAcHTtdZewtml1tNaeKeteDtT2CxByXlEXTv9GLtQkY2hA=s192-c-rg-br100"},{"name":"Milan Foglia","picture":"https://lh3.googleusercontent.com/a/AAcHTtcSuLzPt-hhUP2JqftlcsHfqR7Wtp2Grk4gKKIv0g=s96-c"}],"date":"19 Octobre","time":"11h10","location":"Tour Bretagne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/modern-web-debugging-with-devt.mp4 --props='{"title":"🇺🇸Modern Web Debugging with DevTools","speakers":[{"name":"Jecelyn Yeen","picture":"https://lh3.googleusercontent.com/a/AGNmyxb_JlLu19P-1e6cUOLnt_c7hoUJdAjRwaUdrCGQ=s96-c"}],"date":"19 Octobre","time":"15h10","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/mon-experience-avec-rust-pourq.mp4 --props='{"title":"Mon Expérience avec Rust ! Pourquoi c'\''est un Game Changer ?","speakers":[{"name":"Ayoub ALOUANE","picture":"https://cache.sessionize.com/image/b0cb-200o200o2-YH1o4vLSdgG7nXazZBv56b.jpg"}],"date":"20 Octobre","time":"16h50","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/navigating-the-chaos-a-holisti.mp4 --props='{"title":"Navigating the Chaos: A Holistic Approach to Incident Management","speakers":[{"name":"Hila F","picture":"https://lh3.googleusercontent.com/a/AAcHTtd7O9dKMKsL5PHu6VIXmJTfCbFxK8nXCkWycZcABg=s96-c"}],"date":"19 Octobre","time":"14h00","location":"Tour Bretagne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/pourquoi-et-comment-organiser-.mp4 --props='{"title":"Pourquoi et comment organiser une app en libs avec Nx ?","speakers":[{"name":"Younes Jaaidi","picture":"https://github.com/GDG-Nantes/Devfest2023/assets/525974/adc92d76-a53f-4d62-b004-6895b04880d0"}],"date":"20 Octobre","time":"10h10","location":"Belem"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/programmation-concurrent-et-as.mp4 --props='{"title":"Programmation Concurrent et Asynchrone : le point en Java 21","speakers":[{"name":"José Paumard","picture":"https://lh3.googleusercontent.com/a-/AAuE7mCO1tTjb-bXBtSnWzo1AGC6H-uIzFdvqbKq12SmPC0"}],"date":"19 Octobre","time":"11h10","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/rendu-3d-la-grande-illusion-ex.mp4 --props='{"title":"Rendu 3D, la grande illusion expliquée","speakers":[{"name":"Thomas GUIBERT","picture":"https://github.com/GDG-Nantes/Devfest2023/assets/525974/a481459f-10f6-4ff9-b7c3-5758bd9044cd"}],"date":"20 Octobre","time":"16h50","location":"Titan"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/rendu-front-action-decouvrez-l.mp4 --props='{"title":"Rendu front, action ! Découvrez les différents modes de rendu avec Next.js","speakers":[{"name":"Clémentine ROBERT","picture":"https://lh3.googleusercontent.com/a/AEdFTp7EVEKGri1UevA80y95fq4pJ13iGwjrLnsCTxiZt10=s96-c"},{"name":"Olivier THIERRY","picture":"https://lh6.googleusercontent.com/-nCwPIFQPUqI/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rdEYq9ZHz9xv59b4o9VGbYn-MBaVg/mo/photo.jpg"},{"name":"Ryan BALOJI","picture":"https://avatars.githubusercontent.com/u/34781214?v=4"}],"date":"20 Octobre","time":"14h00","location":"Les Machines"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/semgrep-un-outil-danalyse-secu.mp4 --props='{"title":"Semgrep, un outil d'\''analyse sécurité SAST multi-langage","speakers":[{"name":"Sebastien Gioria","picture":"https://github.com/GDG-Nantes/Devfest2023/assets/525974/ba9b1f5f-f06b-4247-8e83-2076fd6ca362"}],"date":"20 Octobre","time":"9h00","location":"Hangar"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/sous-le-capot-des-navigateurs-.mp4 --props='{"title":"Sous le capot des navigateurs web","speakers":[{"name":"Anthony Le Goas","picture":"https://pbs.twimg.com/profile_images/1450531662232793091/SWqZfLTp_400x400.jpg"}],"date":"20 Octobre","time":"9h00","location":"Tour Bretagne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/spring-framework-60.mp4 --props='{"title":"Spring Framework 6.0","speakers":[{"name":"Stéphane Nicoll","picture":"https://avatars0.githubusercontent.com/u/490484?v=4"}],"date":"20 Octobre","time":"9h00","location":"Titan"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/swiftui-vs-jetpack-compose-par.mp4 --props='{"title":"SwiftUI vs Jetpack Compose par un Ingénieur Android","speakers":[{"name":"Gerard Paligot","picture":"https://lh6.googleusercontent.com/-lM_1hjLdFdE/AAAAAAAAAAI/AAAAAAAABSc/wj6XqgbL-r4/photo.jpg"}],"date":"19 Octobre","time":"10h00","location":"Tour Bretagne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/the-ethics-of-generative-ai.mp4 --props='{"title":"🇺🇸The Ethics of Generative AI","speakers":[{"name":"Jen Looper","picture":"https://user-images.githubusercontent.com/1450004/222968856-68a9cc0e-0bd2-4248-bc92-5596ae16bbdf.jpg"}],"date":"19 Octobre","time":"10h00","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/the-laundromat-quand-les-journ.mp4 --props='{"title":"The laundromat : quand les journalistes deviennent data analystes","speakers":[{"name":"Guillaume Renaudin","picture":"https://avatars.githubusercontent.com/u/4942330?v=4"},{"name":"Antoine Bonneau","picture":"https://lh6.googleusercontent.com/-to_aRrSbIvc/AAAAAAAAAAI/AAAAAAAAABQ/QepXzz8WcD0/photo.jpg"}],"date":"20 Octobre","time":"10h10","location":"Tour Bretagne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/towards-a-carbonaware-cloud.mp4 --props='{"title":"Towards a '\''carbon-aware'\'' cloud.","speakers":[{"name":"Olivier Bierlaire","picture":"https://avatars.githubusercontent.com/u/2562534?v=4"}],"date":"19 Octobre","time":"17h20","location":"Jules Verne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/towards-modern-development-of-.mp4 --props='{"title":"Towards Modern Development of Cloud Applications","speakers":[{"name":"Valentin Deleplace","picture":"https://avatars.githubusercontent.com/u/13508141?v=4"}],"date":"20 Octobre","time":"9h00","location":"Belem"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/unlocking-the-power-of-web-mac.mp4 --props='{"title":"Unlocking the power of Web Machine Learning: Hands-on TensorFlow.js workshop","speakers":[{"name":"Patty O'\''Callaghan","picture":"https://lh3.googleusercontent.com/a/AAcHTtft1LT7FCFs1dgt7HoI5WJcmmAEaWEN-5j19qcD=s96-c"}],"date":"20 Octobre","time":"14h00","location":"L'\''Atelier"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/ux-writer-le-5e-element-de-leq.mp4 --props='{"title":"UX Writer : le 5e élément de l'\''équipe tech / produit","speakers":[{"name":"Ludivine Kasteleyn","picture":"https://lh3.googleusercontent.com/a/AGNmyxb3yNYPnT5GnzwCU01DC7d147eGc1P6u0Cesja0wQ=s96-c"},{"name":"Thibaud Courtoison","picture":"https://pbs.twimg.com/profile_images/1456553725372342273/2FJs-6QR_400x400.jpg"}],"date":"20 Octobre","time":"14h00","location":"Titan"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/voyage-au-coeur-dappwrite-le-b.mp4 --props='{"title":"Voyage au coeur d'\''Appwrite : le backend open-source qui challenge Firebase 🧳","speakers":[{"name":"Mickaël Alves","picture":"https://ca.slack-edge.com/T108ZKPMF-U02G81CC29M-677392b14927-512"},{"name":"Lucas AUDART","picture":"https://lh3.googleusercontent.com/a-/AOh14Giyq3_4Hz9R0BunclQboy24YFJoMK9zBA3YPqSZ=s96-c"}],"date":"19 Octobre","time":"16h20","location":"Hangar"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/web-ml-in-2023-whats-new-with-.mp4 --props='{"title":"🇺🇸Web ML in 2023 - What'\''s new with Machine Learning in JavaScript?","speakers":[{"name":"Jason Mayes","picture":"https://pbs.twimg.com/profile_images/1608707468334616577/e23i2nMf_400x400.jpg"}],"date":"20 Octobre","time":"11h20","location":"Tour Bretagne"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/webassembly-beyond-the-browser.mp4 --props='{"title":"🇺🇸WebAssembly beyond the browser","speakers":[{"name":"Mete Atamel","picture":"https://lh3.googleusercontent.com/a/AAcHTtc8pAon-b1oWPLDFwzpov5qFxMx1pC7QfmU4CXQJ_A=s96-c"}],"date":"20 Octobre","time":"15h10","location":"Titan"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/were-not-doing-design-systems-.mp4 --props='{"title":"🇺🇸We’re Not doing Design Systems Properly and That’s Okay","speakers":[{"name":"Morgane Peng","picture":"https://lh3.googleusercontent.com/a/AGNmyxasWsF1Xmlh-QUMvx8Wza78VFICCxVbpqqE0Z3Jpg=s96-c"}],"date":"19 Octobre","time":"16h20","location":"Titan"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/woop-woop-assassin-de-la-polic.mp4 --props='{"title":"Woop woop assassin de la police...","speakers":[{"name":"François-Xavier Lair","picture":"https://gravatar.com/avatar/104f6c81f962a3525317dfcb58648d3e"}],"date":"19 Octobre","time":"17h20","location":"Belem"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/workshop-sur-lintegration-a-le.mp4 --props='{"title":"Workshop sur l'\''Intégration à l'ère du cloud avec Camel Quarkus","speakers":[{"name":"Alexandre Gallice","picture":"https://avatars.githubusercontent.com/u/22151349?v=4"},{"name":"Kevin Dubois","picture":"https://lh3.googleusercontent.com/a/AEdFTp7YHiZYC4AAyCoqBQod3q5WDu4p1rYDFRim961q=s96-c"}],"date":"19 Octobre","time":"10h00","location":"Hangar"}'
  
pnpm remotion render remotion/index.tsx DevfestNantesTalkLoop out/xtrem-tdd-par-lexemple.mp4 --props='{"title":"Xtrem TDD par l'\''exemple","speakers":[{"name":"Yoan Thirion","picture":"https://lh6.googleusercontent.com/-fFK15b40Woc/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rfmU_ppH5o4woN_ThmnwCJTpFQ9Hg/mo/photo.jpg"},{"name":"Guillaume Faas","picture":"https://avatars.githubusercontent.com/u/59444272?v=4"}],"date":"19 Octobre","time":"16h20","location":"L'\''Atelier"}'
  
